version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    image: danielng01/crawl_lawyer:0.0.2
    ports:
      - "8001:8001"
    command: python manage.py runserver 0.0.0.0:8001
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://crawler:password@db:5432/lawyers_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ROCKETREACH_API_KEY=1bafa4dk4e1f1689bcb51d576e02ea68d25df379
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media
    restart: unless-stopped
    networks:
      - crawler-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=lawyers_db
      - POSTGRES_USER=crawler
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - crawler-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - crawler-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    command: celery -A lawyers_project worker -l info -c 2
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://crawler:password@db:5432/lawyers_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ROCKETREACH_API_KEY=1bafa4dk4e1f1689bcb51d576e02ea68d25df379
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - crawler-network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    command: celery -A lawyers_project beat -l info
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://crawler:password@db:5432/lawyers_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - crawler-network

volumes:
  postgres_data:
  redis_data:

networks:
  crawler-network:
    driver: bridge