# Generated by Django 4.2.7 on 2025-10-23 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('domain', models.CharField(max_length=100)),
                ('practice_area', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('practice_areas', models.TextField(blank=True)),
                ('attorney_details', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('crawl_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('completeness_score', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-crawl_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LawyerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lawyers.lawyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_method', models.CharField(max_length=50)),
                ('contact_details', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('responded', 'Responded'), ('not_interested', 'Not Interested'), ('invalid', 'Invalid Contact')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='lawyers.lawyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['domain'], name='lawyers_law_domain_434f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['state'], name='lawyers_law_state_8996ec_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['practice_area'], name='lawyers_law_practic_e0cca9_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['company_name'], name='lawyers_law_company_9e46a3_idx'),
        ),
    ]
