# Generated by Django 4.2.7 on 2025-10-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['domain', 'state'], name='lawyers_law_domain_3ab5af_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['practice_area', 'city'], name='lawyers_law_practic_287b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['crawl_timestamp'], name='lawyers_law_crawl_t_3e51d3_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['completeness_score'], name='lawyers_law_complet_099379_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['quality_score'], name='lawyers_law_quality_cc9441_idx'),
        ),
    ]
