# Generated by Django 4.2.7 on 2025-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_lawyer_lawyers_law_domain_3ab5af_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='detail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='is_detail_crawled',
            field=models.BooleanField(default=False),
        ),
    ]
