# Generated by Django 4.2.7 on 2025-10-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_lawyer_detail_url_lawyer_is_detail_crawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='attorney_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='badges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='bar_admissions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='contact_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='law_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='licensed_since',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='office_locations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='rising_star',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='super_lawyer_badge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='super_lawyer_years',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
