# Generated by Django 4.2.7 on 2025-10-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_lawyer_attorney_name_lawyer_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='firm_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='lead_counsel_attorneys',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='lead_counsel_images',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='lead_counsel_practice_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='lead_counsel_years',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='related_cities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='related_practice_areas',
            field=models.TextField(blank=True),
        ),
    ]
