# Generated by Django 4.2.7 on 2025-10-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_lawyer_firm_profile_lawyer_lead_counsel_attorneys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerreview',
            name='lawyer',
        ),
        migrations.DeleteModel(
            name='LawyerContact',
        ),
        migrations.DeleteModel(
            name='LawyerReview',
        ),
    ]
