# Generated by Django 4.2.7 on 2025-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0006_remove_lawyerreview_lawyer_delete_lawyercontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='entity_type',
            field=models.CharField(choices=[('law_firm', 'Law Firm'), ('individual_attorney', 'Individual Attorney'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='is_firm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
