# Generated by Django 4.2.7 on 2025-10-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0007_lawyer_entity_type_lawyer_is_firm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='is_firm',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='is_individual',
        ),
    ]
