# Generated by Django 4.2.7 on 2025-10-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0008_remove_lawyer_is_firm_remove_lawyer_is_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketReachLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_name', models.CharField(max_length=200)),
                ('lookup_company', models.CharField(blank=True, max_length=300)),
                ('lookup_domain', models.CharField(blank=True, max_length=100)),
                ('rocketreach_id', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('current_title', models.CharField(blank=True, max_length=200)),
                ('current_company', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_found', 'Not Found')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('lookup_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_credits_used', models.IntegerField(default=0)),
                ('api_request_id', models.CharField(blank=True, max_length=100)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocketreach_lookups', to='lawyers.lawyer')),
            ],
            options={
                'ordering': ['-lookup_timestamp'],
                'indexes': [models.Index(fields=['lawyer'], name='lawyers_roc_lawyer__235ddb_idx'), models.Index(fields=['status'], name='lawyers_roc_status_4a285c_idx'), models.Index(fields=['lookup_timestamp'], name='lawyers_roc_lookup__2d8d7a_idx'), models.Index(fields=['email'], name='lawyers_roc_email_a44119_idx')],
            },
        ),
    ]
