# Generated by Django 4.2.7 on 2025-10-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0009_rocketreachlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocketreachlookup',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rocketreachlookup',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rocketreachlookup',
            name='email_validation_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rocketreachlookup',
            name='job_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rocketreachlookup',
            name='phone_validation_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rocketreachlookup',
            name='region_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rocketreachlookup',
            name='region_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rocketreachlookup',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
