# Generated by Django 4.2.7 on 2025-10-24 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0010_rocketreachlookup_birth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='company_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='employee_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('general', 'General'), ('info', 'Info'), ('contact', 'Contact'), ('support', 'Support'), ('legal', 'Legal'), ('partner', 'Partner'), ('employee', 'Employee')], default='general', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_title', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('validation_status', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source', models.CharField(default='rocketreach', max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_email_records', to='lawyers.lawyer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lawyer'], name='lawyers_com_lawyer__66e81a_idx'), models.Index(fields=['email'], name='lawyers_com_email_2c18ac_idx'), models.Index(fields=['email_type'], name='lawyers_com_email_t_170dfe_idx'), models.Index(fields=['is_verified'], name='lawyers_com_is_veri_cbd2d5_idx'), models.Index(fields=['is_active'], name='lawyers_com_is_acti_b67420_idx')],
                'unique_together': {('lawyer', 'email')},
            },
        ),
    ]
