# Generated by Django 4.2.7 on 2025-10-24 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0011_lawyer_company_emails_lawyer_employee_contacts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyEmail',
        ),
    ]
