# Generated by Django 4.2.7 on 2025-10-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0012_delete_companyemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocketreachlookup',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
