# Generated by Django 4.2.7 on 2025-10-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0013_rocketreachlookup_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='rocketreach_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
