# Generated by Django 4.2.7 on 2025-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0014_allow_null_rocketreach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='current_company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='current_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
