# Generated by Django 4.2.7 on 2025-10-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0015_allow_null_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocketreachlookup',
            name='employee_emails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
