# Generated by Django 4.2.7 on 2025-10-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0016_rocketreachlookup_employee_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketreachlookup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('found', 'Found'), ('failed', 'Failed'), ('not_found', 'Not Found')], default='pending', max_length=20),
        ),
    ]
