# Generated by Django 4.2.7 on 2025-10-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0017_add_found_status_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketReachContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Primary email address', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Full name', max_length=200)),
                ('company', models.CharField(blank=True, help_text='Company name', max_length=300)),
                ('title', models.CharField(blank=True, help_text='Job title', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=50)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('location', models.CharField(blank=True, help_text='Location', max_length=200)),
                ('industry', models.CharField(blank=True, help_text='Industry', max_length=100)),
                ('company_size', models.CharField(blank=True, help_text='Company size', max_length=50)),
                ('experience_years', models.IntegerField(blank=True, help_text='Years of experience', null=True)),
                ('source_url', models.URLField(help_text='RocketReach source URL')),
                ('page_number', models.IntegerField(default=1, help_text='Page number where found')),
                ('position_on_page', models.IntegerField(default=1, help_text='Position on the page')),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score (0-1)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('bounced', 'Bounced'), ('invalid', 'Invalid'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw scraped data')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='lawyers_roc_email_b2bf31_idx'), models.Index(fields=['company'], name='lawyers_roc_company_00f8a0_idx'), models.Index(fields=['status'], name='lawyers_roc_status_5b8976_idx'), models.Index(fields=['created_at'], name='lawyers_roc_created_ea135d_idx')],
            },
        ),
    ]
