# Generated by Django 4.2.7 on 2025-10-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0018_rocketreachcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocketreachcontact',
            name='contact_grade',
            field=models.CharField(blank=True, help_text='Contact quality grade (A, B, C, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='rocketreachcontact',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='Education history'),
        ),
        migrations.AddField(
            model_name='rocketreachcontact',
            name='primary_email',
            field=models.EmailField(blank=True, help_text='Primary email address', max_length=254),
        ),
        migrations.AddField(
            model_name='rocketreachcontact',
            name='profile_id',
            field=models.CharField(blank=True, help_text='RocketReach profile ID', max_length=50),
        ),
        migrations.AddField(
            model_name='rocketreachcontact',
            name='profile_photo',
            field=models.URLField(blank=True, help_text='Profile photo URL'),
        ),
        migrations.AddField(
            model_name='rocketreachcontact',
            name='secondary_email',
            field=models.EmailField(blank=True, help_text='Secondary email address', max_length=254),
        ),
        migrations.AddField(
            model_name='rocketreachcontact',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills and expertise'),
        ),
        migrations.AddField(
            model_name='rocketreachcontact',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='X/Twitter profile URL'),
        ),
        migrations.AddField(
            model_name='rocketreachcontact',
            name='work_experience',
            field=models.JSONField(blank=True, default=list, help_text='Work experience history'),
        ),
    ]
