# Generated by Django 4.2.7 on 2025-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0019_rocketreachcontact_contact_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocketreachcontact',
            name='title_category',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized title category', max_length=50),
        ),
        migrations.AddIndex(
            model_name='rocketreachcontact',
            index=models.Index(fields=['title_category'], name='lawyers_roc_title_c_de356e_idx'),
        ),
    ]
