# Generated by Django 4.2.7 on 2025-10-23 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('domain', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('practice_area', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lawyers_found', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Discovery URL',
                'verbose_name_plural': 'Discovery URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('discovering', 'Discovering URLs'), ('discovery_done', 'Discovery Complete'), ('crawling_listings', 'Crawling Listings'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('domains', models.JSONField(default=list)),
                ('states', models.JSONField(default=list)),
                ('practice_areas', models.JSONField(default=list)),
                ('limit', models.IntegerField(default=10)),
                ('total_urls', models.IntegerField(default=0)),
                ('crawled_urls', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('delay_between_requests', models.FloatField(default=2.0)),
                ('max_retries', models.IntegerField(default=3)),
                ('timeout', models.IntegerField(default=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Source Configuration',
                'verbose_name_plural': 'Source Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='CrawlConfig',
            new_name='CrawlTemplate',
        ),
        migrations.RemoveField(
            model_name='crawltask',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='crawltemplate',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Crawl Template', 'verbose_name_plural': 'Crawl Templates'},
        ),
        migrations.DeleteModel(
            name='CrawlSession',
        ),
        migrations.DeleteModel(
            name='CrawlTask',
        ),
        migrations.AddField(
            model_name='discoveryurl',
            name='source_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_urls', to='crawler.sourceconfiguration'),
        ),
    ]
