# Generated by Django 4.2.7 on 2025-10-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_discoveryurl_sourceconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfiguration',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceconfiguration',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='discoveryurl',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sourceconfiguration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISCOVERING', 'Discovering URLs'), ('DISCOVERY_DONE', 'Discovery Complete'), ('CRAWLING_LISTINGS', 'Crawling Listings'), ('PAUSED', 'Paused'), ('RETRYING', 'Retrying After Error'), ('FAILED', 'Failed'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
