# Generated by Django 4.2.7 on 2025-10-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_sourceconfiguration_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceconfiguration',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='sourceconfiguration',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='sourceconfiguration',
            name='practice_areas',
        ),
        migrations.RemoveField(
            model_name='sourceconfiguration',
            name='states',
        ),
        migrations.AddField(
            model_name='sourceconfiguration',
            name='selectors',
            field=models.JSONField(default=dict, help_text='JSON field storing XPath selectors for different data fields'),
        ),
        migrations.AddField(
            model_name='sourceconfiguration',
            name='start_urls',
            field=models.JSONField(default=list, help_text="List of start URLs to crawl, e.g., ['www.lawinfo.com/personal-injury/arizona/chandler/', 'www.lawinfo.com/personal-injury/new-mexico/albuquerque/']"),
        ),
        migrations.AlterField(
            model_name='sourceconfiguration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CRAWLING', 'Crawling'), ('PAUSED', 'Paused'), ('RETRYING', 'Retrying After Error'), ('FAILED', 'Failed'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
