# Generated by Django 4.2.7 on 2025-10-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_remove_sourceconfiguration_domains_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrawlTemplate',
        ),
    ]
