# Generated by Django 4.2.7 on 2025-10-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_delete_crawltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryurl',
            name='current_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discoveryurl',
            name='has_next_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryurl',
            name='next_page_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='discoveryurl',
            name='total_pages',
            field=models.IntegerField(default=1),
        ),
    ]
