# Generated by Django 4.2.7 on 2025-10-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_discoveryurl_current_page_discoveryurl_has_next_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoveryurl',
            name='has_next_page',
        ),
        migrations.RemoveField(
            model_name='discoveryurl',
            name='next_page_url',
        ),
    ]
